# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'HackDuke2019' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  #Auto Layout library
  pod 'SnapKit', '~> 4.0.0'
  #library for downloading and caching images from API
  #pod 'Kingfisher', '~> 3.0'
  #Send Message TextInput
  pod 'Toolbar'
  #Messages TableView
  pod 'ReverseExtension'
  pod 'ApiAI'
  
end

